chore(actions): try to fix again cuz invalid

diff --git a/.forgejo/workflows/wf-json-linter.yml b/.forgejo/workflows/wf-json-linter.yml
--- a/.forgejo/workflows/wf-json-linter.yml
+++ b/.forgejo/workflows/wf-json-linter.yml
@@ -18,4 +18,7 @@ jobs:
           sparse-checkout: |
             modpacks
       - name: Lint JSON
-        run: find . -name "*.json" | while read f; do python3 -m json.tool "$f" > /dev/null || echo "FAILED: $f"; done
+        run: |
+          find . -name "*.json" | while read f; do
+            python3 -m json.tool "$f" > /dev/null || echo "FAILED: $f"
+          done
